run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - nilerr
    - goprintffuncname

  disable:
    - errcheck
    - gofmt
    - unparam
    - nakedret
    - errorlint
    - exhaustive
    - gocyclo
    - funlen

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  staticcheck:
    checks: ["all"]

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  new: false

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

severity:
  default-severity: error
